---
title: "Duration Figure for Documentation - Deer Creek Example"
author: "[Skyler Lewis](mailto:slewis@flowwest.com)"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
    toc_depth: 3
    number_sections: false
    math_method:
      engine: webtex
      url: https://latex.codecogs.com/svg.image?
---

```{r setup}
library(tidyverse)
library(sf)
library(terra)
library(tidyterra)
library(ggspatial)
theme_set(theme_minimal())

# import duration info from inundation-duration.Rmd
durhsi_by_first_inundating_flow <- readRDS(here::here("data-raw", "results", "durhsi_by_model_q.Rds"))
```

Calculate and plot first inundating flow

```{r deer-duration}
if(!file.exists(here::here("data-raw", "temp", "deer_first_inundating_flow.tif"))) {
  
  dir.create(here::here("data-raw", "temp", "deer_model_output"), recursive = TRUE)
  
  drive_file_by_id("1rmMw6PXJGS0-ui52eaotABCSlJsZOzvr", dir=here::here("data-raw", "temp", "deer_model_output")) |>
    archive::archive_extract(dir=here::here("data-raw", "temp", "deer_model_output"))
  
  filenames <- tribble(~flow_cfs, ~timestep,
          100, "15NOV2018 06 00 00",
          250, "15NOV2018 16 00 00",
          300, "16NOV2018 02 00 00",
          400, "16NOV2018 12 00 00",
          500, "16NOV2018 22 00 00",
          600, "17NOV2018 08 00 00",
         1000, "17NOV2018 18 00 00",
         3000, "18NOV2018 04 00 00",
         5000, "18NOV2018 14 00 00",
         6000, "19NOV2018 00 00 00",
         7000, "19NOV2018 10 00 00",
         9000, "19NOV2018 20 00 00",
        10000, "20NOV2018 06 00 00",
        11000, "20NOV2018 16 00 00",
        12000, "21NOV2018 02 00 00",
        13000, "21NOV2018 12 00 00",
        14000, "21NOV2018 22 00 00",
        15000, "22NOV2018 08 00 00") |>
    mutate(depth =    here::here("data-raw", paste0("temp/deer_model_output/Depth (",timestep,").vrt")),
           velocity = here::here("data-raw", paste0("temp/deer_model_output/Velocity (",timestep,").vrt")))
  
  depth_rasters <- filenames |> 
    select(flow_cfs, depth) |>
    deframe()

  first_inundating_flow <- 
    names(depth_rasters) |>
    lapply(function(q) (terra::ifel(terra::rast(depth_rasters[[q]]) > 0, 1, NA) * as.numeric(q))) |>
    terra::rast() |>
    terra::app(fun = "min", na.rm=TRUE) 
  
  first_inundating_flow |>
    terra::writeRaster(here::here("data-raw", "temp", "deer_first_inundating_flow.tif"), overwrite=T)
  
} else {
  
    first_inundating_flow <-
    terra::rast(here::here("data-raw", "temp", "deer_first_inundating_flow.tif"))

}

first_inundating_flow |> terra::set.names("flow_cfs")

ggplot() + 
  geom_spatraster(data=first_inundating_flow, aes(fill = flow_cfs)) + 
  scale_fill_viridis_c(name = "Flow (cfs)", 
                       na.value = NA) +
  labs(title = "First Inundating Flow",
       subtitle = "Deer Creek")
```

```{r}
ggsave(here::here("vignettes", "figures", "duration_deer_fif.png"))
```

Max inundated

```{r deer-max-inundated}
if(!file.exists(here::here("data-raw", "temp", "deer_max_days_inundated.tif"))) {

  deer_max_days_inundated <-
    durhsi_by_first_inundating_flow |> 
    filter(river=="Deer Creek") |>
    select(model_q, max_days_inundated) |>
    deframe()
  
  max_days_inundated <- 
    first_inundating_flow |> 
    terra::app(function(x) deer_max_days_inundated[as.character(x)])
  
  max_days_inundated |>
    terra::writeRaster(here::here("data-raw", "temp", "deer_max_days_inundated.tif"), overwrite=T)

} else {
  
  max_days_inundated <-
    terra::rast(here::here("data-raw", "temp", "deer_max_days_inundated.tif"))

}

max_days_inundated |> terra::set.names("n_days")

ggplot() + 
  geom_spatraster(data=max_days_inundated, aes(fill = n_days)) + 
  scale_fill_viridis_c(name = "# Days",
                       na.value = NA) +
  labs(title = "Maximum Inundation",
       subtitle = "Deer Creek")
```

```{r}
ggsave(here::here("vignettes", "figures", "duration_deer_max.png"))
```

```{r}
knitr::knit_exit()
```

Calculate and plot duration HSIs
```{r deer-duration-calcs}
deer_dhsis_vl <-
  durhsi_by_first_inundating_flow |> filter(river=="Deer Creek") |>
  select(model_q, avg_durhsi_vl) |>
  deframe()

deer_dhsis_vf <-
  durhsi_by_first_inundating_flow |> filter(river=="Deer Creek") |>
  select(model_q, avg_durhsi_vf) |>
  deframe()

deer_avg_days_inundated <-
  durhsi_by_first_inundating_flow |> filter(river=="Deer Creek") |>
  select(model_q, avg_days_inundated) |>
  deframe()

deer_max_days_inundated <-
  durhsi_by_first_inundating_flow |> filter(river=="Deer Creek") |>
  select(model_q, max_days_inundated) |>
  deframe()

deer_dhsi_components <- terra::rast(list(
  "fif" = first_inundating_flow,
  "vf" = first_inundating_flow |> terra::app(function(x) deer_dhsis_vf[as.character(x)]),
  "vl" = first_inundating_flow |> terra::app(function(x) deer_dhsis_vl[as.character(x)]),
  "di_avg" = first_inundating_flow |> terra::app(function(x) deer_avg_days_inundated[as.character(x)])),
  "di_max" = first_inundating_flow |> terra::app(function(x) deer_max_days_inundated[as.character(x)]))
```

```{r deer-duration-hsi}
terra::rast(list(deer_dhsi_components$vf, deer_dhsi_components$vl)) |> plot(range=c(0,1))
```

```{r deer-duration-max}
deer_dhsi_components$di_max |> plot(main="Maximum Length of Continuous Inundation (days)")
```

```{r deer-duration-avg}
deer_dhsi_components$di_avg |> plot(main="Average Length of Continuous Inundation (days)")
```

<mark>TODO: show di_avg and di_max converted into the three types of duration HSI
etc.

```{r}
cls_vl <- valley_lowland |> 
  st_transform(st_crs(first_inundating_flow)) |> 
  st_crop(st_bbox(first_inundating_flow)) |> 
  terra::rasterize(first_inundating_flow, values=1, background=0)

deer_dhsi <- terra::ifel(cls_vl==1, deer_dhsi_components$vl, deer_dhsi_components$vf)

deer_dhsi |> plot(main="Duration HSI Factor")

dhsi_packed <- terra::wrap(deer_dhsi)
```
