name: Deploy pkgdown

on:
  push:
  branches:
  - main  # or your default branch

jobs:
  deploy:
  runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
- uses: r-lib/actions/setup-r@v2
- name: Install dependencies
run: R -e 'install.packages(c("remotes", "pkgdown")); remotes::install_deps()'
- name: Build pkgdown site
run: R -e 'pkgdown::deploy_to_branch(new_process = TRUE)'
